// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: resturant_data_proxy.proto

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductName string `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Nums        int64  `protobuf:"varint,2,opt,name=nums,proto3" json:"nums,omitempty"`
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetNums() int64 {
	if x != nil {
		return x.Nums
	}
	return 0
}

// The request message containing the user's name.
type AddOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*OrderItem `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	User     *User        `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *AddOrderReq) Reset() {
	*x = AddOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderReq) ProtoMessage() {}

func (x *AddOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderReq.ProtoReflect.Descriptor instead.
func (*AddOrderReq) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *AddOrderReq) GetProducts() []*OrderItem {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *AddOrderReq) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// The response message containing the greetings
type AddOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddOrderRsp) Reset() {
	*x = AddOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRsp) ProtoMessage() {}

func (x *AddOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRsp.ProtoReflect.Descriptor instead.
func (*AddOrderRsp) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *AddOrderRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddDishReq) Reset() {
	*x = AddDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishReq) ProtoMessage() {}

func (x *AddDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishReq.ProtoReflect.Descriptor instead.
func (*AddDishReq) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{4}
}

type AddDishRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddDishRsp) Reset() {
	*x = AddDishRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDishRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishRsp) ProtoMessage() {}

func (x *AddDishRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishRsp.ProtoReflect.Descriptor instead.
func (*AddDishRsp) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{5}
}

type GetDishesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDishesReq) Reset() {
	*x = GetDishesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesReq) ProtoMessage() {}

func (x *GetDishesReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesReq.ProtoReflect.Descriptor instead.
func (*GetDishesReq) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{6}
}

type GetDishesRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDishesRsp) Reset() {
	*x = GetDishesRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesRsp) ProtoMessage() {}

func (x *GetDishesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesRsp.ProtoReflect.Descriptor instead.
func (*GetDishesRsp) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{7}
}

type UpdateDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDishReq) Reset() {
	*x = UpdateDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDishReq) ProtoMessage() {}

func (x *UpdateDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDishReq.ProtoReflect.Descriptor instead.
func (*UpdateDishReq) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{8}
}

type UpdateDishRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDishRsp) Reset() {
	*x = UpdateDishRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDishRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDishRsp) ProtoMessage() {}

func (x *UpdateDishRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDishRsp.ProtoReflect.Descriptor instead.
func (*UpdateDishRsp) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{9}
}

type DeleteDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDishReq) Reset() {
	*x = DeleteDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDishReq) ProtoMessage() {}

func (x *DeleteDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDishReq.ProtoReflect.Descriptor instead.
func (*DeleteDishReq) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{10}
}

type DeleteDishRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDishRsp) Reset() {
	*x = DeleteDishRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDishRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDishRsp) ProtoMessage() {}

func (x *DeleteDishRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDishRsp.ProtoReflect.Descriptor instead.
func (*DeleteDishRsp) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{11}
}

type SelectDishesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SelectDishesReq) Reset() {
	*x = SelectDishesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectDishesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectDishesReq) ProtoMessage() {}

func (x *SelectDishesReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectDishesReq.ProtoReflect.Descriptor instead.
func (*SelectDishesReq) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{12}
}

type SelectDishesRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SelectDishesRsp) Reset() {
	*x = SelectDishesRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectDishesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectDishesRsp) ProtoMessage() {}

func (x *SelectDishesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectDishesRsp.ProtoReflect.Descriptor instead.
func (*SelectDishesRsp) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{13}
}

type UpdateOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOrderReq) Reset() {
	*x = UpdateOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderReq) ProtoMessage() {}

func (x *UpdateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderReq.ProtoReflect.Descriptor instead.
func (*UpdateOrderReq) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{14}
}

type UpdateOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOrderRsp) Reset() {
	*x = UpdateOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRsp) ProtoMessage() {}

func (x *UpdateOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRsp.ProtoReflect.Descriptor instead.
func (*UpdateOrderRsp) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{15}
}

type AddDishToCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddDishToCartReq) Reset() {
	*x = AddDishToCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDishToCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishToCartReq) ProtoMessage() {}

func (x *AddDishToCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishToCartReq.ProtoReflect.Descriptor instead.
func (*AddDishToCartReq) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{16}
}

type AddDishToCartRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddDishToCartRsp) Reset() {
	*x = AddDishToCartRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDishToCartRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishToCartRsp) ProtoMessage() {}

func (x *AddDishToCartRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishToCartRsp.ProtoReflect.Descriptor instead.
func (*AddDishToCartRsp) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{17}
}

type RemoveDishFromCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveDishFromCartReq) Reset() {
	*x = RemoveDishFromCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveDishFromCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDishFromCartReq) ProtoMessage() {}

func (x *RemoveDishFromCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDishFromCartReq.ProtoReflect.Descriptor instead.
func (*RemoveDishFromCartReq) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{18}
}

type RemoveDishFromCartRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveDishFromCartRsp) Reset() {
	*x = RemoveDishFromCartRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resturant_data_proxy_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveDishFromCartRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDishFromCartRsp) ProtoMessage() {}

func (x *RemoveDishFromCartRsp) ProtoReflect() protoreflect.Message {
	mi := &file_resturant_data_proxy_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDishFromCartRsp.ProtoReflect.Descriptor instead.
func (*RemoveDishFromCartRsp) Descriptor() ([]byte, []int) {
	return file_resturant_data_proxy_proto_rawDescGZIP(), []int{19}
}

var File_resturant_data_proxy_proto protoreflect.FileDescriptor

var file_resturant_data_proxy_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x65, 0x73, 0x74, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x3e, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x42, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x22, 0x66, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x24,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0c, 0x0a,
	0x0a, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x22, 0x0c, 0x0a, 0x0a, 0x41,
	0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x73, 0x70, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x0f, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x11, 0x0a,
	0x0f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73,
	0x52, 0x73, 0x70, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x44, 0x69,
	0x73, 0x68, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x22, 0x12, 0x0a, 0x10, 0x41,
	0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x73, 0x70, 0x22,
	0x17, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x73, 0x68, 0x46, 0x72, 0x6f,
	0x6d, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x44, 0x69, 0x73, 0x68, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x72, 0x74, 0x52, 0x73,
	0x70, 0x32, 0x90, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x08, 0x41,
	0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64,
	0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x73, 0x70, 0x22, 0x00, 0x32, 0xb3, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x74, 0x12, 0x4d, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x12, 0x1c,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x44,
	0x69, 0x73, 0x68, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73,
	0x68, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x12,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x73, 0x68, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61,
	0x72, 0x74, 0x12, 0x21, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x73, 0x68, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x73, 0x68, 0x46, 0x72, 0x6f,
	0x6d, 0x43, 0x61, 0x72, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x32, 0xde, 0x02, 0x0a, 0x04, 0x44,
	0x69, 0x73, 0x68, 0x12, 0x3b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x12, 0x16,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x44,
	0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x44, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x12, 0x19,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x68, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x69, 0x73, 0x68, 0x12, 0x19, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0c,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x67, 0x0a, 0x1b, 0x69,
	0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resturant_data_proxy_proto_rawDescOnce sync.Once
	file_resturant_data_proxy_proto_rawDescData = file_resturant_data_proxy_proto_rawDesc
)

func file_resturant_data_proxy_proto_rawDescGZIP() []byte {
	file_resturant_data_proxy_proto_rawDescOnce.Do(func() {
		file_resturant_data_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_resturant_data_proxy_proto_rawDescData)
	})
	return file_resturant_data_proxy_proto_rawDescData
}

var file_resturant_data_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_resturant_data_proxy_proto_goTypes = []interface{}{
	(*User)(nil),                  // 0: helloworld.User
	(*OrderItem)(nil),             // 1: helloworld.OrderItem
	(*AddOrderReq)(nil),           // 2: helloworld.AddOrderReq
	(*AddOrderRsp)(nil),           // 3: helloworld.AddOrderRsp
	(*AddDishReq)(nil),            // 4: helloworld.AddDishReq
	(*AddDishRsp)(nil),            // 5: helloworld.AddDishRsp
	(*GetDishesReq)(nil),          // 6: helloworld.GetDishesReq
	(*GetDishesRsp)(nil),          // 7: helloworld.GetDishesRsp
	(*UpdateDishReq)(nil),         // 8: helloworld.UpdateDishReq
	(*UpdateDishRsp)(nil),         // 9: helloworld.UpdateDishRsp
	(*DeleteDishReq)(nil),         // 10: helloworld.DeleteDishReq
	(*DeleteDishRsp)(nil),         // 11: helloworld.DeleteDishRsp
	(*SelectDishesReq)(nil),       // 12: helloworld.SelectDishesReq
	(*SelectDishesRsp)(nil),       // 13: helloworld.SelectDishesRsp
	(*UpdateOrderReq)(nil),        // 14: helloworld.UpdateOrderReq
	(*UpdateOrderRsp)(nil),        // 15: helloworld.UpdateOrderRsp
	(*AddDishToCartReq)(nil),      // 16: helloworld.AddDishToCartReq
	(*AddDishToCartRsp)(nil),      // 17: helloworld.AddDishToCartRsp
	(*RemoveDishFromCartReq)(nil), // 18: helloworld.RemoveDishFromCartReq
	(*RemoveDishFromCartRsp)(nil), // 19: helloworld.RemoveDishFromCartRsp
}
var file_resturant_data_proxy_proto_depIdxs = []int32{
	1,  // 0: helloworld.AddOrderReq.products:type_name -> helloworld.OrderItem
	0,  // 1: helloworld.AddOrderReq.user:type_name -> helloworld.User
	2,  // 2: helloworld.Order.AddOrder:input_type -> helloworld.AddOrderReq
	14, // 3: helloworld.Order.UpdateOrder:input_type -> helloworld.UpdateOrderReq
	16, // 4: helloworld.Cart.AddDishToCart:input_type -> helloworld.AddDishToCartReq
	18, // 5: helloworld.Cart.RemoveDishFromCart:input_type -> helloworld.RemoveDishFromCartReq
	4,  // 6: helloworld.Dish.AddDish:input_type -> helloworld.AddDishReq
	8,  // 7: helloworld.Dish.UpdateDish:input_type -> helloworld.UpdateDishReq
	10, // 8: helloworld.Dish.DeleteDish:input_type -> helloworld.DeleteDishReq
	12, // 9: helloworld.Dish.SelectDishes:input_type -> helloworld.SelectDishesReq
	6,  // 10: helloworld.Dish.GetDishes:input_type -> helloworld.GetDishesReq
	2,  // 11: helloworld.Order.AddOrder:output_type -> helloworld.AddOrderReq
	15, // 12: helloworld.Order.UpdateOrder:output_type -> helloworld.UpdateOrderRsp
	17, // 13: helloworld.Cart.AddDishToCart:output_type -> helloworld.AddDishToCartRsp
	19, // 14: helloworld.Cart.RemoveDishFromCart:output_type -> helloworld.RemoveDishFromCartRsp
	5,  // 15: helloworld.Dish.AddDish:output_type -> helloworld.AddDishRsp
	9,  // 16: helloworld.Dish.UpdateDish:output_type -> helloworld.UpdateDishRsp
	11, // 17: helloworld.Dish.DeleteDish:output_type -> helloworld.DeleteDishRsp
	13, // 18: helloworld.Dish.SelectDishes:output_type -> helloworld.SelectDishesRsp
	7,  // 19: helloworld.Dish.GetDishes:output_type -> helloworld.GetDishesRsp
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_resturant_data_proxy_proto_init() }
func file_resturant_data_proxy_proto_init() {
	if File_resturant_data_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resturant_data_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDishRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishesRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDishRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDishRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectDishesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectDishesRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDishToCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDishToCartRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveDishFromCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resturant_data_proxy_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveDishFromCartRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resturant_data_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_resturant_data_proxy_proto_goTypes,
		DependencyIndexes: file_resturant_data_proxy_proto_depIdxs,
		MessageInfos:      file_resturant_data_proxy_proto_msgTypes,
	}.Build()
	File_resturant_data_proxy_proto = out.File
	file_resturant_data_proxy_proto_rawDesc = nil
	file_resturant_data_proxy_proto_goTypes = nil
	file_resturant_data_proxy_proto_depIdxs = nil
}
