// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: restaurant_data_proxy.proto

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type AddOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AddOrderReq) Reset() {
	*x = AddOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderReq) ProtoMessage() {}

func (x *AddOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderReq.ProtoReflect.Descriptor instead.
func (*AddOrderReq) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrderReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type AddOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddOrderRsp) Reset() {
	*x = AddOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRsp) ProtoMessage() {}

func (x *AddOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRsp.ProtoReflect.Descriptor instead.
func (*AddOrderRsp) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrderRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddDishReq) Reset() {
	*x = AddDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishReq) ProtoMessage() {}

func (x *AddDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishReq.ProtoReflect.Descriptor instead.
func (*AddDishReq) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{2}
}

type AddDishRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddDishRsp) Reset() {
	*x = AddDishRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDishRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishRsp) ProtoMessage() {}

func (x *AddDishRsp) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishRsp.ProtoReflect.Descriptor instead.
func (*AddDishRsp) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{3}
}

type GetDishesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDishesReq) Reset() {
	*x = GetDishesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesReq) ProtoMessage() {}

func (x *GetDishesReq) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesReq.ProtoReflect.Descriptor instead.
func (*GetDishesReq) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{4}
}

type GetDishesRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDishesRsp) Reset() {
	*x = GetDishesRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesRsp) ProtoMessage() {}

func (x *GetDishesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesRsp.ProtoReflect.Descriptor instead.
func (*GetDishesRsp) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{5}
}

type UpdateDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDishReq) Reset() {
	*x = UpdateDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDishReq) ProtoMessage() {}

func (x *UpdateDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDishReq.ProtoReflect.Descriptor instead.
func (*UpdateDishReq) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{6}
}

type UpdateDishRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDishRsp) Reset() {
	*x = UpdateDishRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDishRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDishRsp) ProtoMessage() {}

func (x *UpdateDishRsp) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDishRsp.ProtoReflect.Descriptor instead.
func (*UpdateDishRsp) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{7}
}

type DeleteDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDishReq) Reset() {
	*x = DeleteDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDishReq) ProtoMessage() {}

func (x *DeleteDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDishReq.ProtoReflect.Descriptor instead.
func (*DeleteDishReq) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{8}
}

type DeleteDishRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDishRsp) Reset() {
	*x = DeleteDishRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDishRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDishRsp) ProtoMessage() {}

func (x *DeleteDishRsp) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDishRsp.ProtoReflect.Descriptor instead.
func (*DeleteDishRsp) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{9}
}

type SelectDishesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SelectDishesReq) Reset() {
	*x = SelectDishesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectDishesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectDishesReq) ProtoMessage() {}

func (x *SelectDishesReq) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectDishesReq.ProtoReflect.Descriptor instead.
func (*SelectDishesReq) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{10}
}

type SelectDishesRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SelectDishesRsp) Reset() {
	*x = SelectDishesRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restaurant_data_proxy_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectDishesRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectDishesRsp) ProtoMessage() {}

func (x *SelectDishesRsp) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_data_proxy_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectDishesRsp.ProtoReflect.Descriptor instead.
func (*SelectDishesRsp) Descriptor() ([]byte, []int) {
	return file_restaurant_data_proxy_proto_rawDescGZIP(), []int{11}
}

var File_restaurant_data_proxy_proto protoreflect.FileDescriptor

var file_restaurant_data_proxy_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x21, 0x0a, 0x0b, 0x41, 0x64, 0x64,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x22, 0x0c, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x73,
	0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x73,
	0x70, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52,
	0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68,
	0x52, 0x73, 0x70, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69,
	0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x73, 0x70, 0x32, 0x47, 0x0a, 0x05, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64,
	0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x22, 0x00, 0x32, 0xde, 0x02, 0x0a, 0x04, 0x44, 0x69, 0x73, 0x68, 0x12, 0x3b, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x12, 0x16, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x41, 0x64,
	0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x12, 0x19, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x44, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x12, 0x19,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x68, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12,
	0x18, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73,
	0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x67, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_restaurant_data_proxy_proto_rawDescOnce sync.Once
	file_restaurant_data_proxy_proto_rawDescData = file_restaurant_data_proxy_proto_rawDesc
)

func file_restaurant_data_proxy_proto_rawDescGZIP() []byte {
	file_restaurant_data_proxy_proto_rawDescOnce.Do(func() {
		file_restaurant_data_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_restaurant_data_proxy_proto_rawDescData)
	})
	return file_restaurant_data_proxy_proto_rawDescData
}

var file_restaurant_data_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_restaurant_data_proxy_proto_goTypes = []interface{}{
	(*AddOrderReq)(nil),     // 0: helloworld.AddOrderReq
	(*AddOrderRsp)(nil),     // 1: helloworld.AddOrderRsp
	(*AddDishReq)(nil),      // 2: helloworld.AddDishReq
	(*AddDishRsp)(nil),      // 3: helloworld.AddDishRsp
	(*GetDishesReq)(nil),    // 4: helloworld.GetDishesReq
	(*GetDishesRsp)(nil),    // 5: helloworld.GetDishesRsp
	(*UpdateDishReq)(nil),   // 6: helloworld.UpdateDishReq
	(*UpdateDishRsp)(nil),   // 7: helloworld.UpdateDishRsp
	(*DeleteDishReq)(nil),   // 8: helloworld.DeleteDishReq
	(*DeleteDishRsp)(nil),   // 9: helloworld.DeleteDishRsp
	(*SelectDishesReq)(nil), // 10: helloworld.SelectDishesReq
	(*SelectDishesRsp)(nil), // 11: helloworld.SelectDishesRsp
}
var file_restaurant_data_proxy_proto_depIdxs = []int32{
	0,  // 0: helloworld.Order.AddOrder:input_type -> helloworld.AddOrderReq
	2,  // 1: helloworld.Dish.AddDish:input_type -> helloworld.AddDishReq
	6,  // 2: helloworld.Dish.UpdateDish:input_type -> helloworld.UpdateDishReq
	8,  // 3: helloworld.Dish.DeleteDish:input_type -> helloworld.DeleteDishReq
	10, // 4: helloworld.Dish.SelectDishes:input_type -> helloworld.SelectDishesReq
	4,  // 5: helloworld.Dish.GetDishes:input_type -> helloworld.GetDishesReq
	0,  // 6: helloworld.Order.AddOrder:output_type -> helloworld.AddOrderReq
	3,  // 7: helloworld.Dish.AddDish:output_type -> helloworld.AddDishRsp
	7,  // 8: helloworld.Dish.UpdateDish:output_type -> helloworld.UpdateDishRsp
	9,  // 9: helloworld.Dish.DeleteDish:output_type -> helloworld.DeleteDishRsp
	11, // 10: helloworld.Dish.SelectDishes:output_type -> helloworld.SelectDishesRsp
	5,  // 11: helloworld.Dish.GetDishes:output_type -> helloworld.GetDishesRsp
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_restaurant_data_proxy_proto_init() }
func file_restaurant_data_proxy_proto_init() {
	if File_restaurant_data_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_restaurant_data_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDishRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishesRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDishRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDishRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectDishesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restaurant_data_proxy_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectDishesRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_restaurant_data_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_restaurant_data_proxy_proto_goTypes,
		DependencyIndexes: file_restaurant_data_proxy_proto_depIdxs,
		MessageInfos:      file_restaurant_data_proxy_proto_msgTypes,
	}.Build()
	File_restaurant_data_proxy_proto = out.File
	file_restaurant_data_proxy_proto_rawDesc = nil
	file_restaurant_data_proxy_proto_goTypes = nil
	file_restaurant_data_proxy_proto_depIdxs = nil
}
